### DISCUSSION TITLE
269

### DISCUSSION THREAD

**Discussion by jojoldu** [jojoldu/blog-comments#716] [Comments]
http://jojoldu.tistory.com/269

**Comment by jojoldu** [comment]
작성자: 제리루즈

2번씩 정주행 완료했습니다ㅎㅎ 다음편도 기대할게요

**Comment by jojoldu** [comment]
작성자: 창천향로 창천향로

고맙습니다^^ 잘 준비해서 다음편 올리겠습니다!
매번 감사합니다^^

**Comment by gonghojin** [comment]
글이 얼마 안 남았네요..ㅠ 아쉽네요 - 잘배우고 갑니다~

**Comment by jojoldu** [comment]
@gonghojin 아고 매번 감사합니다 ㅠ :)

**Comment by gonghojin** [comment]
창천항로님 질문 몇개만 드려도 될까요??..
1. spring.profiles.include를 포함시킨 후 profiles명이 real-db로 찍히는 데요. 문제는 real-db로 찍혀서 deploy.sh에서 if문에서 set1, set2 둘다 해당되지 않기 떄문에 else 값만 찍혀서 set1만 배포합니다..그래서 배포시 application이 중단되는데. 어디 부분에서 설정이 잘못된 건가요?

2. ec2 서버 내에서  deploy.sh을 실행시킬 경우 jar파일의 소유권이 ec2로 잡혀서 kill -15 줄 때 문제가 없는데, local에서 commit을 통해 deploy.sh를 실행시킬 경우 root 권한으로 잡혀서 kill시 자격없음으로 set1, set2 둘다 서비스 중인 상태가 되는데요. deploy.sh에서 sudo kill~를 추가하는 게 맞는 건가요? 아니면 다른 부분에서 해야될 설정을 실수한 건가요?

**Comment by jojoldu** [comment]
@gonghojin 안녕하세요!?

1. 1번의 경우 profile에 real-db와 set1 혹은 set2가 함께 포함되어있는데요. 
여기서 filter 조건으로 set1 혹은 set2 중에 있는것만 반환하도록 코드를 변경하시면 될것 같습니다.

WebRestController.java

```java
    @GetMapping("/profile")
    public String getProfile () {
        return Arrays.stream(env.getActiveProfiles())
                .filter(e -> "set1".equals(e) || "set2".equals"e))
                .findFirst()
                .orElse("");
    }
```

2.  sudo kill로 하셔도 됩니다 :)

**Comment by gonghojin** [comment]
어우 감사합니다~ㅎ 일요일 저녁이네요 ㅠ 남은 주말 잘보내셔요

**Comment by gonghojin** [comment]
안녕하세요 창천향로님 질문이 있는데요. 
travis build할 때 문제없는 소스여도 error가 날 때 있나요??.
local에서 test하고 commit하면 가끔 error가 발생하는데 재빌드하면 문제없이 지나가네요

**Comment by jojoldu** [comment]
@gonghojin 아 넵 저도 그럴때가 간혹 있습니다. 아직원인은 찾지 못했습니다 ㅠ

**Comment by kimgun95** [comment]
springboot 2.4 부터는 profile에 대한 설정이 조금 바뀌었어요. 혹시 설정이 어려운 분들은 아래와 같이 설정을 하면 도움이 될겁니다.
set1,set2,real-db profile 설정할때는 아래와 같이 했어요.
```
---
spring:
  config:
    activate:
      on-profile: set1
server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: set2
server:
  port: 8082

---
spring:
  config:
    activate:
      on-profile: real-db
```
그리고 프로젝트 내부 application.yml 파일에서 set1,set2가 read-db를 include하는 설정은 아래와 같이 했습니다.
```
spring:
  profiles:
    group:
      set1: real-db
      set2: real-db
```
아무도 댓글에 적어두지 않아서 누군가에겐 도움이 되길 바랍니다!
