### ISSUE TITLE
http://jojoldu.tistory.com/234

### ISSUE THREAD

**Issue by jojoldu** [jojoldu/blog-comments#197]
http://jojoldu.tistory.com/234

**Comment by jojoldu** [comment]
작성자: ssossohow

감사합니다^^ 유용하게 사용하였습니다.

**Comment by jojoldu** [comment]
작성자: 창천향로 창천향로

도움이 되셨다니 제가 더 감사합니다^^

**Comment by tramyu** [comment]
Spring Boot 2.0을 공부하려고 초기 셋팅하면서 위의 예제를 보고 따라하고 있는데 2.0부터 기본 커넥션풀이 Tomcat에서 HikariCP로 변경되어서 그런지 DataSoruce를 못찾아서 적용하느라 한참 삽질했네요 관련 내용도 추가해주시면 다른분들이 삽질을 줄일 수 있을것 같습니다 ㅠ

저는 올려주신 코드 그대로에서 아래의 내용만 변경했습니다.

```java
@Configuration
@Profile("local")
public class H2ServerConfiguration {

    @Bean
    @ConfigurationProperties("spring.datasource") // yml의 설정값을 Set한다.
    public DataSource dataSource() throws SQLException {
        Server.createTcpServer("-tcp", "-tcpAllowOthers", "-tcpPort", "9092").start();
        return new com.zaxxer.hikari.HikariDataSource();
    }
}
```

```
spring:
  profiles:
    active: local

---
spring:
  profiles: local

  datasource:
    platform: h2
    jdbc-url: jdbc:h2:tcp://localhost:9092/mem:testdb;MVCC=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: H2
    show-sql: false
    hibernate:
      ddl-auto: create-drop
```

hikari는 url로 주면 작동이 안되고.. jdbc-url을 줘야 작동해서 jdbc-url로 변경했습니다.
